spring.application.name=montecarlo-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/montecarlo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

spring.mail.host=smtp.gmail.com
# CAMBIO 1: Usamos el puerto 465 (SSL) en lugar del 587
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME:lunadepluton911@gmail.com}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
# CAMBIO 2: Apagamos STARTTLS y encendemos SSL explícito
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true

# CAMBIO 3: Le damos 10 segundos de paciencia a Railway en lugar de 5
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000